name: Docker publish dispatcher

run-name: Docker publish (${{ inputs.architecture }})

on:
  workflow_dispatch:
    inputs:
      architecture:
        description: 'architecture'
        required: true
        type: choice
        options:
          - arm64
          - amd64
          - x86_64

jobs:
  dispatch:
    uses: ./.github/workflows/docker-publish-workflow.yml
    with:
      architecture: ${{ inputs.architecture }}
    secrets: inherit